// Generated by Wrangler on Wed Jul 31 2024 21:53:30 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
